services:
  mariadb:
    build:
      context: ./srcs/requirements/mariadb
    env_file: .env # Loads MYSQL_DATABASE and MYSQL_USER
    environment:
      # These point to the files mounted below.
      # Your MariaDB startup script will need to read these files.
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - /juitz/login/data/mariadb:/var/lib/mysql
      # Mount the secret files as read-only into the container
      - ./secrets/db_password.txt:/run/secrets/db_password:ro
      - ./secrets/db_root_password.txt:/run/secrets/db_root_password:ro
    networks:
      - inception_net
    restart: always

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
    env_file: .env # Loads DB_HOST, DB_NAME, DB_USER
    environment:
      # Your WordPress startup script will need to read this file.
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - /juitz/login/data/wordpress:/var/www/html
      - ./secrets/db_password.txt:/run/secrets/db_password:ro
    depends_on:
      - mariadb
    networks:
      - inception_net
    restart: always

  nginx:
    build:
      context: ./srcs/requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      # Nginx also needs access to the WordPress files to serve static assets (images, CSS).
      # We mount the SAME volume here.
      - /juitz/login/data/wordpress:/var/www/html
    depends_on:
      - wordpress

networks:
  inception_net:
    driver: bridge