services:
  mariadb:
    build:
      context: ./srcs/requirements/mariadb
    container_name: mariadb
    env_file: .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - /home/juitz/data/mariadb:/var/lib/mysql
      - ./secrets/db_password.txt:/run/secrets/db_password:ro
      - ./secrets/db_root_password.txt:/run/secrets/db_root_password:ro
    networks:
      - inception_net
    restart: always

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
    container_name: wordpress
    env_file: .env
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
    volumes:
      - /home/juitz/data/wordpress:/var/www/html
      - ./secrets/db_password.txt:/run/secrets/db_password:ro
    depends_on:
      - mariadb
    networks:
      - inception_net
    restart: always

  nginx:
    build:
      context: ./srcs/requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - /home/juitz/data/wordpress:/var/www/html
    depends_on:
      - wordpress

networks:
  inception_net:
    driver: bridge

# volumes:
#   wordpress_data:
#   mariadb_data: